# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Connecting Dots
email: artem.pyanykh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Math, programming, productivity -- these are the topics that interest me the most.
  And that is what I may write about from time to time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://artempyanykh.github.io" # the base hostname & protocol for your site
twitter_username: artem_pyanykh
github_username:  artempyanykh
linkedin_username: artempyanykh
repository: https://github.com/artempyanykh/artempyanykh.github.io.git

# Build settings
markdown: kramdown
